# Generated by Django 5.0.2 on 2024-03-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_author_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_image',
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
